     swagUserName = //input[@id='user-name']
	 swagPassword = //input[@id='password']
	 swagLoginBtn = //input[@id='login-button']
	 productText = //span[text()='Products']
	 backPack = //div[text()='Sauce Labs Backpack']/ancestor::div[@class='inventory_item']/descendant::button
	 bikeLight = //div[text()='Sauce Labs Bike Light']/ancestor::div[@class='inventory_item']/descendant::button
	 clickOnCart = //a[@class='shopping_cart_link']
	 checkOutOption = //button[@id='checkout']
	 chckoutOptionCSS = button.btn.btn_action.btn_medium.checkout_button
	 firstName = //input[@id='first-name']
	 lastName = //input[@id='last-name']
	 postalCode = //input[@id='postal-code']
	 continueBtn = //input[@id='continue']
	 finishBtn = //button[@id='finish']
	 thankYouText = //h2[text()='Thank you for your order!']